create table "public"."floats" (
    "id" bigint generated by default as identity not null
);


alter table "public"."floats" enable row level security;

create table "public"."float_floats_groups" (
    "float_id" bigint generated by default as identity not null,
    "group_id" bigint not null
);


alter table "public"."float_floats_groups" enable row level security;

create table "public"."float_groups" (
    "id" bigint generated by default as identity not null,
    "user" bigint,
    "name" character varying,
    "description" text
);


alter table "public"."float_groups" enable row level security;

create table "public"."users" (
    "address" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.floats USING btree (id);

CREATE UNIQUE INDEX floats_groups_pkey ON public.float_floats_groups USING btree (float_id, group_id);

CREATE UNIQUE INDEX groups_pkey ON public.float_groups USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (address);

alter table "public"."floats" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."float_floats_groups" add constraint "floats_groups_pkey" PRIMARY KEY using index "floats_groups_pkey";

alter table "public"."float_groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."float_floats_groups" add constraint "floats_groups_float_id_fkey" FOREIGN KEY (float_id) REFERENCES floats(id) ON DELETE CASCADE not valid;

alter table "public"."float_floats_groups" validate constraint "floats_groups_float_id_fkey";

alter table "public"."float_floats_groups" add constraint "floats_groups_group_id_fkey" FOREIGN KEY (group_id) REFERENCES float_groups(id) not valid;

alter table "public"."float_floats_groups" validate constraint "floats_groups_group_id_fkey";

alter table "public"."float_groups" add constraint "groups_user_fkey" FOREIGN KEY ("user") REFERENCES users(address) not valid;

alter table "public"."float_groups" validate constraint "groups_user_fkey";


