create table "public"."claims" (
    "float_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "event_id" bigint,
    "user_address" bigint not null
);


alter table "public"."claims" enable row level security;

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "creator_address" bigint not null
);


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX claims_pkey ON public.claims USING btree (float_id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

alter table "public"."claims" add constraint "claims_pkey" PRIMARY KEY using index "claims_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."claims" add constraint "claims_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) not valid;

alter table "public"."claims" validate constraint "claims_event_id_fkey";


